name: connection-manager-scarpa
base: core22                           
version: '1.2.21-7'
summary: A slimmed down desktop application for managing SSH and SFTP.
description: |
  **SCARPA Connection Manager** is a secure, GTK3-based desktop application designed to streamline
  how you manage and launch SSH and SFTP connections. It organizes server configurations into
  folders, automates login sequences, and protects your sensitive data with a robust GnuPG-based
  encryption system.
  
  **Core Features:**
  * **Server & Folder Management:** Organize servers hierarchically. Supports drag-and-drop.
  * **Embedded VTE Terminal:** Features smart copy/paste and auto-resize sync.
  * **Connection Automation:** Automate login sequences or use standard key files.
  * **Dual-Pane SFTP Manager:** Visually manage files side-by-side.
  * **Super Safe Encryption:** All credentials are encrypted using AES256 via GnuPG.
  * **Customization:** Customize the font, color palette, and scrollback buffer.
  * **Data Portability:** Export and import configurations easily.
  
  A GTK-based SSH/SFTP session manager.
  Riposa in pace, Aquila di Filottrano. Sarai sempre con noi!
   	
icon: data/icons/hicolor/512x512/apps/scarpa_icon.png

grade: stable 
confinement: strict 

apps:
  connection-manager-scarpa:   
    command: src/scarpa_connection_manager.py
    extensions: [gnome]
    desktop: data/snap_desktop.desktop
    plugs:
      - network
      - home
      - ssh-keys
      - ssh-public-keys
      - password-manager-service
      - removable-media
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH

layout:
  /usr/share/scarpa_connection_manager:
    bind: $SNAP/usr/share/scarpa_connection_manager
    
  /usr/share/tcltk:
    bind: $SNAP/usr/share/tcltk

parts:
  scarpa:
    plugin: dump
    source: .
    stage-packages:
      - python3
      - python3-gi
      - gir1.2-gtk-3.0
      - gir1.2-vte-2.91
      - python3-paramiko
      - gnupg1                         
      - expect
      - openssh-client
      - tcl
      
    organize:
      data/icons/hicolor/: usr/share/icons/hicolor/
      docs/folder.png: usr/share/scarpa_connection_manager/folder.png
      docs/server.png: usr/share/scarpa_connection_manager/server.png
      docs/user_guide.html: usr/share/scarpa_connection_manager/user_guide.html
